### ISSUE TITLE
Arithmetics operation update

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#167]
@forman: I like the diff op, but I still disagree with the arithmetic op. We should really move to an op, where users can specify a normal expression which we either

* eval without globals but with a safe locals environment, see `cate.util.safe_eval()`
* and/or  use numexpr for boosting performance.

**Comment by forman** [comment]
Idea: use new `new_expression_op()` function and register it as operation `compute` with `expression` as only input.

Problems:

This leads to a workflow step 
* with no other step inputs than `expression`, therefore it appears as it wouldn't have any dependencies to other steps. But actually, the expression may refer to *any* other step output, be referencing it by its resource name.
* with a single return value of unknown data type, because an expression may evaluate to any Python data type. 

The latter problem may be avoided by offering dedicated `compute_<type>` operations.
The first may be avoided by treating steps containing a `compute` operation (or one containing general Python expressions evaluated in the context of the workflow) as being dependent on *all* other steps. This way they would be re-invoked if *any other* step input changes.
