### ISSUE TITLE
Use Case #2 happy path - long term average on cloud dataset fails

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#441]
### Expected behavior

Ran use case #2 happy path using GUI

### Actual behaviour
When applying long term average operation to cfc variable in cloud dataset, there was an error:
![lta](https://user-images.githubusercontent.com/29569434/31011725-3f53744a-a507-11e7-8fef-7c1ca7af6bdf.PNG)

Traceback:
[lta traceback.txt](https://github.com/CCI-Tools/cate/files/1343927/lta.traceback.txt)

### Steps to reproduce the problem
See:
[steps to reproduce.docx](https://github.com/CCI-Tools/cate/files/1343930/steps.to.reproduce.docx)

### Specifications
cate-0.9.0-dev.7
Windows 7 Professional

**Comment by JanisGailis** [comment]
UC2 CLI happy path runs as expected on 0.9.dev7 and the current master.

It seems that when invoked from the GUI the dataset being opened is not CF decoded by xarray. That would explain why we have an int64 as time dimension, as opposed to the expected datetime64. It's probably 'seconds since'.

I think Helen is right and this must be the same issue as #443.

**Comment by JanisGailis** [comment]
I disagree with the ops label. The CLI happy paths are working as expected, hence, I don't think the problem is in ops.

**Comment by HelenClifton** [comment]
Confirmed fixed in cate 1.0.0-dev.3
