### ISSUE TITLE
support-help windows cate1.0 gui exiting with error

### ISSUE THREAD

**Issue by nsashi** [CCI-Tools/cate#469]
### Expected behavior
Windows Cate Desktop to open
![cate_error](https://user-images.githubusercontent.com/2811771/32345143-53624572-c02f-11e7-82d0-4707fc7aaf7e.jpg)

### Actual behavior
Exits with error "Cate-Desktop Internal error, Cate Service exited with code 255"

### Steps to reproduce the problem
1. Install cate core first (with uncheck for Anaconda path) in directories a)Other than C:\ and C:\
2. Install cate_windows_gui
3. Run cate_gui
4. gui exits with above error and shows 'waiting for cate service response' in the background

### Specifications 
Windows 10, 64 bit

**Comment by forman** [comment]
@nsashi sorry for the late reply. The bug is known and already fixed for the next release.

Here is a workaround: Assuming `CATE_DIR` is the directory where you have installed Cate Core. The please locate `%CATE_DIR%\Scripts\cate-cli.bat` and change the line

    cd %CATE_BIN%\..

to
    
    cd /D %CATE_BIN%\..

That should fix the issue. See also https://github.com/CCI-Tools/cate-conda/blob/30c9ec511b3a97ced2d0b3109f3407145e4b6e1a/recipes/cate-cli/cate-cli.bat#L7

**Comment by forman** [comment]
Closing this as of #479.
