### ISSUE TITLE
Time axis scrambled

### ISSUE THREAD

**Issue by kjpearson** [CCI-Tools/cate#548]
### Expected behaviour

I've successfully opened the SST CCI dataset (#538 seems to have self-resolved!)  and created a place mark. Clicking on the "create a time series from selected place mark" should produce a nice graph.

### Actual behaviour

I actually get the attached graph. The time axis for the data doesn't seem to be interpreted properly as it is daily data for a number of years rather than what is shown. The points also connected up in a scrambled order.

![tseries_graph](https://user-images.githubusercontent.com/5889217/37150680-7a49b60e-22ca-11e8-8bec-c3ff1d3062e0.png)

### Specifications 

Cate v2.0-dev1 iMac

**Comment by kjpearson** [comment]
I get the same behaviour if I use the series_point operation. 
Dataset: the two years 2000-2001
point: -164,3 , 
var: analysed_sst,
method: nearest.

**Comment by forman** [comment]
It's ok, that's art.

**Comment by forman** [comment]
Could someone reproduce this?

**Comment by JanisGailis** [comment]
I can reproduce this. This is related to #443 
The same Cate code (dev8) runs fine when an environment with xarray == 10.0 is used, but issues with time decoding appear when xarray >= 10.1 is used. This seems to be because of a change in xarray 10.1, when CF time decoding part of ``netcdf-python`` library became a separate package ``netcdftime``, which in turn became an optional dependency for xarray. http://xarray.pydata.org/en/stable/whats-new.html
