### ISSUE TITLE
animated map (including side-by-side visualisation)

### ISSUE THREAD

**Issue by lkeupp** [CCI-Tools/cate#85]
it should be possible to see animations of temporally evolving data as an animated maps.
by displaying two of those maps side-by-side supports data comparison and correlation analysis

**Comment by JanisGailis** [comment]
Is this essential for API and CLI, or just the GUI interface? I think @forman has to chime in!

**Comment by forman** [comment]
For the GUI, it is essential, not now but at some point in time. For API and CLI it is desirable. Since we can save individual maps as png/gif, people can create their own animated gifs or mpeg videas with extra software. However, this is a core feature I would expect from a climate analysis toolbox and it is also required by the original SoW.

**Comment by JanisGailis** [comment]
From ops point of view considered a subset of #86. Duplicating the functionality of Window managers or the GUI in showing two plots side by side is considered out of scope here.
