### ISSUE TITLE
Support Icesheets Antarctica dataset in Zarr Data Store

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#983]
The Zarr Data Store contains data from the ODP that has been converted into the zarr format. There are two ICESHEETS datasets in the Zarr data store, one referring to Antarctica. For the purposes of this issue, we say that a dataset is supported when
1. it can be opened in cate
2. it can be opened in cate with a spatial subset
3. its content can be written to disk
4. its data can be displayed in cate

The ICESHEETS Antarctica dataset cannot be displayed in cate. The error message is: Last two dimensions of variable time_dec: ('time',).; . There is no traceback.

**Comment by forman** [comment]
Cate can open it now, but cannot 

- create spatial subsets or display spatial tiles, because of polat stereographic projectsion and x, y vars/coords
- create temporal subsets because, the time variable is called `time_dec`

![image](https://user-images.githubusercontent.com/206773/118679741-6d676180-b7fe-11eb-81d7-4c069fedf549.png)
