### ISSUE TITLE
Support Icesheets Greenland dataset in Zarr Data Store

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#984]
The Zarr Data Store contains data from the ODP that has been converted into the zarr format. There are two ICESHEETS datasets in the Zarr data store, one referring to Greenland. For the purposes of this issue, we say that a dataset is supported when
1. it can be opened in cate
2. it can be opened in cate with a spatial subset
3. its content can be written to disk
4. its data can be displayed in cate

The ICESHEETS Greenland cannot be opened in cate at all. The traceback is:

[2021-04-29 08:54:35] Request: 
open_dataset(datasetid=ESACCI-ICESHEETS_Greenland_GMB-2003-2016-v1.1.zarr, time_range=('2003-01-01', '2003-01-11'), var_names=['end_time', 'end_time'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 306, in test_open_ds
    dataset, _ = open_dataset(dataset_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 432, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 39, in select_subset
    dataset = select_temporal_subset(dataset, time_range=time_range)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 116, in select_temporal_subset
    raise ValueError(f'cannot compute temporal subset: variable "{time_name}" not found in dataset')
ValueError: cannot compute temporal subset: variable "time" not found in dataset

**Comment by forman** [comment]
Cate can open them now, but cannot
- create spatial subsets or image tiles because lon, lat is called longitude, latitude and are 1D

![image](https://user-images.githubusercontent.com/206773/118680848-612fd400-b7ff-11eb-942f-570691a2cdc2.png)

However, it is possible to create temporal subsets:

![image](https://user-images.githubusercontent.com/206773/118680960-7c9adf00-b7ff-11eb-8d4e-3ec83ffdaef7.png)
